# Generated by Django 2.1.4 on 2019-02-25 12:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField(blank=True)),
                ('type', models.CharField(choices=[('image', '图像'), ('video', '视频')], default='image', max_length=8)),
                ('real_time', models.DateTimeField(blank=True, null=True, verbose_name='真实创建时间')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name_plural': '文章',
                'verbose_name': '文章',
            },
        ),
        migrations.CreateModel(
            name='File',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file_name', models.CharField(max_length=32)),
                ('file', models.FileField(blank=True, upload_to='uploadFile')),
                ('imageDescription', models.CharField(blank=True, default='', max_length=128, verbose_name='文件描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name_plural': '文件',
                'verbose_name': '文件',
            },
        ),
        migrations.CreateModel(
            name='Inventory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('signature', models.CharField(blank=True, max_length=32, verbose_name='签名')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('article', models.ManyToManyField(blank=True, related_name='inventory_article', to='weChart.Article')),
            ],
            options={
                'verbose_name_plural': '朋友圈',
                'verbose_name': '朋友圈',
            },
        ),
        migrations.CreateModel(
            name='Palette',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('images_name', models.CharField(blank=True, max_length=32, null=True)),
                ('images', models.ImageField(blank=True, upload_to='uploadImages', verbose_name='图片')),
                ('imageDescription', models.CharField(blank=True, default='', max_length=128, verbose_name='图片描述')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parents', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='image', to='weChart.Article')),
            ],
            options={
                'verbose_name_plural': '图片',
                'verbose_name': '图片',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('friends', models.ManyToManyField(blank=True, related_name='_user_friends_+', to='weChart.User')),
                ('ownInventory', models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='weChart.Inventory', verbose_name='朋友圈')),
            ],
            options={
                'verbose_name_plural': '用户',
                'verbose_name': '用户',
            },
        ),
        migrations.AddField(
            model_name='article',
            name='file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weChart.File'),
        ),
    ]
