# Generated by Django 2.1.4 on 2019-02-20 06:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weChart', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'verbose_name': '文章', 'verbose_name_plural': '文章'},
        ),
        migrations.AlterModelOptions(
            name='file',
            options={'verbose_name': '文件', 'verbose_name_plural': '文件'},
        ),
        migrations.AlterModelOptions(
            name='inventory',
            options={'verbose_name': '朋友圈', 'verbose_name_plural': '朋友圈'},
        ),
        migrations.AlterModelOptions(
            name='palette',
            options={'verbose_name': '图片', 'verbose_name_plural': '图片'},
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'verbose_name': '用户', 'verbose_name_plural': '用户'},
        ),
        migrations.RemoveField(
            model_name='article',
            name='parents',
        ),
        migrations.AddField(
            model_name='inventory',
            name='article',
            field=models.ManyToManyField(blank=True, to='weChart.Article'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='signature',
            field=models.CharField(blank=True, max_length=32, verbose_name='签名'),
        ),
        migrations.AlterField(
            model_name='user',
            name='ownInventory',
            field=models.OneToOneField(blank=True, on_delete=django.db.models.deletion.CASCADE, to='weChart.Inventory', verbose_name='朋友圈'),
        ),
    ]
