# Generated by Django 2.1.4 on 2019-02-20 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weChart', '0002_auto_20190220_1421'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='real_time',
            field=models.DateTimeField(blank=True, null=True, verbose_name='真实创建时间'),
        ),
        migrations.AlterField(
            model_name='palette',
            name='images_name',
            field=models.CharField(max_length=32, null=True),
        ),
    ]
