# Generated by Django 2.1.4 on 2019-02-20 08:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weChart', '0003_auto_20190220_1641'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='file',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='weChart.File'),
        ),
        migrations.AlterField(
            model_name='palette',
            name='images_name',
            field=models.CharField(blank=True, max_length=32, null=True),
        ),
    ]
