# Generated by Django 2.1.4 on 2019-02-28 02:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserInformatization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('show_name', models.CharField(blank=True, max_length=32, null=True)),
                ('signature', models.CharField(blank=True, max_length=128, null=True)),
                ('location', models.CharField(blank=True, max_length=32, null=True)),
                ('weChat', models.CharField(blank=True, max_length=32, null=True)),
                ('github_url', models.CharField(blank=True, max_length=32, null=True)),
                ('link', models.CharField(blank=True, max_length=32, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user',
            name='informatization',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='blog.UserInformatization'),
        ),
    ]
