# Generated by Django 2.1.4 on 2018-12-07 07:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_time', models.DateTimeField(auto_now_add=True)),
                ('ip', models.CharField(max_length=128, null=True)),
                ('location', models.CharField(max_length=128, null=True)),
                ('entrance', models.CharField(max_length=128, null=True)),
            ],
        ),
    ]
