# Generated by Django 2.1.4 on 2019-02-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='access_tools',
            field=models.CharField(max_length=128000, null=True),
        ),
    ]
