# Generated by Django 2.1.4 on 2018-12-07 08:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_history'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='area',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='city',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='country',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='isp',
            field=models.CharField(max_length=128, null=True),
        ),
        migrations.AddField(
            model_name='history',
            name='region',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
