# Generated by Django 2.1.4 on 2019-02-25 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190225_2013'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='area',
            field=models.CharField(max_length=128000, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='city',
            field=models.CharField(max_length=128000, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='country',
            field=models.CharField(max_length=128000, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='entrance',
            field=models.CharField(max_length=128000, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='ip',
            field=models.CharField(max_length=128000, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='isp',
            field=models.CharField(max_length=128000, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='location',
            field=models.CharField(max_length=128000, null=True),
        ),
        migrations.AlterField(
            model_name='history',
            name='region',
            field=models.CharField(max_length=128000, null=True),
        ),
    ]
