# Generated by Django 2.1.4 on 2019-02-28 03:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20190228_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='userinformatization',
            name='image_url',
            field=models.ImageField(blank=True, null=True, upload_to='userImages', verbose_name='图片'),
        ),
    ]
