# Generated by Django 2.1.4 on 2018-12-07 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_auto_20181207_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='access_tools',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
