# Generated by Django 2.1.4 on 2018-12-07 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_history_access_tools'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='JSON',
            field=models.TextField(null=True),
        ),
    ]
