# Generated by Django 2.1.4 on 2018-12-10 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_history_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='Pond_IP',
            fields=[
                ('ip', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('visit_number', models.IntegerField(default=1, editable=False, null=True, verbose_name='来访次数')),
            ],
        ),
    ]
