# Generated by Django 2.1.4 on 2018-12-10 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_pond_ip'),
    ]

    operations = [
        migrations.AddField(
            model_name='pond_ip',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='上次来访时间'),
        ),
        migrations.AlterField(
            model_name='pond_ip',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, verbose_name='开始时间'),
        ),
    ]
