# Generated by Django 2.1.4 on 2018-12-10 12:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_messageboard'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlackList',
            fields=[
                ('ip', models.CharField(max_length=128, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='上次拦截时间')),
                ('intercept_number', models.IntegerField(default=1, editable=False, null=True, verbose_name='拦截次数')),
            ],
        ),
    ]
