# Generated by Django 2.1.4 on 2018-12-10 12:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0009_blacklist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blacklist',
            name='intercept_number',
            field=models.IntegerField(default=0, editable=False, null=True, verbose_name='拦截次数'),
        ),
        migrations.AlterField(
            model_name='blacklist',
            name='ip',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='ip_list', serialize=False, to='blog.Pond_IP'),
        ),
    ]
