# Generated by Django 2.1.4 on 2018-12-11 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0011_auto_20181211_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='history',
            name='action',
            field=models.TextField(null=True),
        ),
    ]
